baseURL = "https://csyakamoz.github.io"
languageCode = "en-us"
title = "Legen—wait for it—dary! Legendary!"
theme = "yinyang"
DefaultContentLanguage = "cn"
enableRobotsTXT = true
canonifyURLs = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true
    [markup.highlight]
        style = "solarized-light"
        lineNos = true
        lineNumbersInTable = false

[author]
  name = "CsYakamoz"

[languages]
  [languages.cn]
    contentDir = "content"
    languageName = "Chinese"
    weight = 1

[params]
headTitle = "Awesome"
description = "Suit up!"
mainSections = ["post", "tags"]
lazyImage = true

[[params.socials]]
name = "Github"
link = "https://github.com/CsYakamoz"
[[params.socials]]
name = "LeetCode"
link = "https://leetcode.com/CsYakamoz/"
[[params.socials]]
name = "About"
link = "./about"
